I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/y1_s1.rpy", line 50, in script call
    call map
  File "game/script.rpy", line 243, in script call
    call map
  File "game/script.rpy", line 243, in script call
    call map
  File "game/script.rpy", line 243, in script call
    call map
  File "game/script.rpy", line 241, in script call
    e "Please click the next location you would like to visit."
  File "game/script.rpy", line 137, in script
    player "I'm not sure, what do you do here?"
Exception: Sayer 'player' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/y1_s1.rpy", line 50, in script call
    call map
  File "game/script.rpy", line 243, in script call
    call map
  File "game/script.rpy", line 243, in script call
    call map
  File "game/script.rpy", line 243, in script call
    call map
  File "game/script.rpy", line 241, in script call
    e "Please click the next location you would like to visit."
  File "game/script.rpy", line 137, in script
    player "I'm not sure, what do you do here?"
  File "renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'player' is not defined.

Windows-10-10.0.22000
Ren'Py 7.4.11.2266
CS 1.0
Wed Feb 23 12:23:03 2022
